version: '3.8'

services:
  backend:
    build: .
    container_name: lunex-backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      # Пробрасываем папку с базой данных и прокси наружу,
      # чтобы при перезапуске/обновлении контейнера данные не удалились
      - ./data:/app/data
      - ./proxies.txt:/app/proxies.txt
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production
      - PORT=5000
      - REDIS_URL=redis://redis:6379
      - MONGO_URI=mongodb://mongodb:27017/lunex
    depends_on:
      - redis
      - mongodb

  mongodb:
    image: mongo:6
    container_name: lunex-mongo
    command: ["mongod", "--quiet"]
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: lunex-redis
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  mongo_data:
